initial draft of PR-GUIDELINES
cloudposse/.github pull request #30
Opened 2024-01-31 00:22 UTC by joe-niland

## what
* Braindump of information related to contributing to Cloud Posse Terraform modules

## why
* Provide a guide for reviewers and authors

## references
* None

2024-01-31 01:39 UTC, osterman commented on PR-GUIDELINES.md
> +1. Fill out the PR template
I assume this refers to the file [`PULL_REQUEST_TEMPLATE.md`](https://github.com/cloudposse/.github/blob/main/.github/PULL_REQUEST_TEMPLATE.md)
```suggestion
1. Fill out the PR template
```

I'll make a note we should have a GitHub Action validate that the description does not match this file.

2024-01-31 01:41 UTC, osterman commented on PR-GUIDELINES.md
> +
```suggestion
You may also need to install gomplate: https://docs.gomplate.ca/installing/ 

3. When updating variables, update the variable description if it could be made clearer, and especially if a new map/object attribute is added

```

2024-01-31 01:42 UTC, osterman commented on PR-GUIDELINES.md
> +Examples:
```suggestion
#### Examples:
```

2024-01-31 01:43 UTC, osterman commented on PR-GUIDELINES.md
> +To avoid errors like `The "count" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created. To work around this, use
```suggestion
To avoid errors like `The "count" value depends on resource attributes that cannot be determined until apply time, so Terraform cannot predict how many instances will be created. To work around this, use the -target argument to first apply only the resources that the count depends on.` Cloud Posse has [standardised](https://github.com/cloudposse/terraform-aws-security-group/wiki/Naming-Conventions,-Deprecating-Inputs,-Optional-Inputs#optional-inputs) on using lists where inputs may be empty, and they determine the existence of another resource.
```

2024-01-31 01:44 UTC, osterman commented on PR-GUIDELINES.md
> +- AWS_SESSION_TOKEN
```suggestion
- `AWS_ACCESS_KEY_ID`
- `AWS_SECRET_ACCESS_KEY`
- `AWS_SESSION_TOKEN`
```

2024-01-31 01:45 UTC, osterman commented on PR-GUIDELINES.md
> +Using aws-vault or Leapp or some other method, populate the following AWS credential environment variables for a suitable account:
```suggestion
Using [Leapp](https://docs.cloudposse.com/howto/geodesic/authenticate-with-leapp/), [aws-vault](https://docs.cloudposse.com/howto/geodesic/authenticate-with-aws-vault/) or or some other method, populate the following AWS credential environment variables for a suitable account:
```

2024-01-31 01:46 UTC, osterman commented on PR-GUIDELINES.md
> +You may also need to install gomplate: https://docs.gomplate.ca/installing/ 3. When updating variables, update the variable description if it could be made clearer, and especially if a new map/object
```suggestion
You may also need to install gomplate: https://docs.gomplate.ca/installing/ 

3. When updating variables, update the variable description if it could be made clearer, and especially if a new map/object attribute is added
```

2024-01-31 11:20 UTC, Gowiem commented on CONTRIBUTING.md
> +The currently proposed labels are:
I'd suggest we add an "On Hold" label as well that would allow us to mark a PR as not ready to merge, but we don't want to go into the stale/auto-close cycle.

2024-01-31 11:27 UTC, Gowiem commented on CONTRIBUTING.md
> +To avoid errors like `The "count" value depends on resource attributes that cannot be determined until apply time, so Terraform cannot predict how many instances will be created. To work around this,
Good callout. 

When the same happens with `map` it's also a PITA and something that feels like we have a standard on. @aknysh described the go to approach here and I think he put it succinctly: https://sweetops.slack.com/archives/CB6GHNLG0/p1705692959914809?thread_ts=1705692678.037929&cid=CB6GHNLG0

Once you get this merged, I'll follow up with some docs on that.

2024-01-31 14:35 UTC, hans-d commented on CONTRIBUTING.md
> +1. `Patch`: A minor, backward compatible change. Increments patch version, e.g. 1.0.**1**
there is likely some automation that can help with the semver (sugesting) bit

2024-01-31 14:35 UTC, hans-d commented on CONTRIBUTING.md
> +The currently proposed labels are:
Even having these labels should be monitored. Perhaps only delay the first "stale" mention, but otherwise would say: just run the stale bit anyway. We should be able to remove that label and start a new period to get it marked stale again instead.

2024-01-31 14:35 UTC, hans-d commented on CONTRIBUTING.md
> +You may also need to install gomplate: https://docs.gomplate.ca/installing/
we should be able to auto-update those things, saves "oops, forgotten". And by automating it, we know it's the most recent version.

2024-01-31 14:35 UTC, hans-d commented on CONTRIBUTING.md
> +To avoid errors like `The "count" value depends on resource attributes that cannot be determined until apply time, so Terraform cannot predict how many instances will be created. To work around this,
can we apply standard/automated linting rules ?

2024-01-31 14:35 UTC, hans-d commented on CONTRIBUTING.md
> +            description = <<-EOT
Use of EOT/EOF for longer descriptions should also be a recommendation...

2024-01-31 22:23 UTC, joe-niland commented on CONTRIBUTING.md
> +            description = <<-EOT
@hans-d (thanks for the review!) it's included in https://docs.cloudposse.com/reference/best-practices/terraform-best-practices/#use-indented-heredoc-syntax

2024-02-03 00:27 UTC, joe-niland commented on CONTRIBUTING.md
> +The currently proposed labels are:
@Gowiem thanks for the review.
I think @osterman 's idea was to use the presence of any of the other labels in the list as an indicator that it shouldn't be closed due to staleness. But I may have misunderstood.

@hans-d yeah that's definitely worth considering otherwise the other labels are just an alt route to things never being dealt with!

2024-02-03 00:30 UTC, joe-niland commented on CONTRIBUTING.md
> +To avoid errors like `The "count" value depends on resource attributes that cannot be determined until apply time, so Terraform cannot predict how many instances will be created. To work around this,
@Gowiem yes, it also happens with lists and maps. 
Re: that link, yes it would be great to have recommendations on the `The true and false result expressions must have consistent types` error too.

2024-02-03 00:31 UTC, joe-niland commented on CONTRIBUTING.md
> +To avoid errors like `The "count" value depends on resource attributes that cannot be determined until apply time, so Terraform cannot predict how many instances will be created. To work around this,
@hans-d I think it might be difficult to automate these ones because the issues show up when the inputs depend on external state.

2024-02-03 00:32 UTC, joe-niland commented on CONTRIBUTING.md
> +You may also need to install gomplate: https://docs.gomplate.ca/installing/
@Nuru [fixed](https://github.com/cloudposse/build-harness/pull/375) this yesterday. @Gowiem if you get a chance, please test the fix on your machine.

2024-02-03 00:33 UTC, joe-niland commented on CONTRIBUTING.md
> +1. `Patch`: A minor, backward compatible change. Increments patch version, e.g. 1.0.**1**
@hans-d that would be awesome. Have you seen any suitable actions?

2024-02-03 01:37 UTC, hans-d commented on CONTRIBUTING.md
> +To avoid errors like `The "count" value depends on resource attributes that cannot be determined until apply time, so Terraform cannot predict how many instances will be created. To work around this,
Linters should be able to identify such cases. but seeing that eg tflint does not have something for this (yet?)

2024-02-20 23:19 UTC, Gowiem commented on CONTRIBUTING.md
> +You may also need to install gomplate: https://docs.gomplate.ca/installing/
I believe this is working now 👍 

Let's cut this line: 

```suggestion
```

2024-02-20 23:20 UTC, Gowiem approved these changes
@joe-niland this looks great to me and it has been sitting for a bit, you have my approval, but let's get one more before merge so someone from CP can approve this as well 👍

2024-02-21 00:17 UTC, joe-niland commented
> @joe-niland this looks great to me and it has been sitting for a bit, you have my approval, but let's get one more before merge so someone from CP can approve this as well 👍

Thanks @Gowiem! 
@osterman are you OK with the latest changes?

2024-02-21 19:58 UTC, hans-d commented on CONTRIBUTING.md
> +make docker/test
Good to know: wont work on arm / mac with apple sillicon

2024-02-22 02:04 UTC, joe-niland commented on CONTRIBUTING.md
> +make docker/test
@hans-d what behaviour do you see on this platform?

2024-02-22 11:07 UTC, hans-d commented on CONTRIBUTING.md
> +make docker/test
It directly fails, as no arm image is available. There seems to be a simple fix, but that code needs to be in each repo (unsure yet if there is a master repos where the test generics are pushed from)

2024-02-23 05:10 UTC, Nuru commented on CONTRIBUTING.md
> +1. `Patch`: A minor, backward compatible change. Increments patch version, e.g. 1.0.**1**
We use [release-drafter](https://github.com/release-drafter/release-drafter) to automatically generate version numbers based on labels applied to the PR. All you have to do is add the appropriate labels. If there are no labels, "minor" is used.

We do not have automation to determine the labels. 

We also still have a lot of modules on v0, which has different rules. Only Cloud Posse engineers should move a module from v0 to v1, and usually we prefer that it not be a breaking change. In fact, it's not uncommon for v1 to be just a new label for the current release, prompted by the desire to release a v2 that has a breaking change.


My point of view is that the primary reason for adhering to [semver](https://semver.org/) is automation. If a change is made that for some reason should not be applied without a human review, then that is a Major change. According to semver, if there is a breaking change, that should be a Major change, and usually we follow that, but we might make a major release due to a change in policy (such as changing default behavior).

On the other side, it should always be safe to apply a patch version automatically without review. If a change fixes a bug in a way that might cause a service interruption or other problem for people relying on the buggy behavior, then that may be a minor or even major change, even though bugfixes can usually be released as patches. 

In the end it is a balance between wanting to warn people the release needs manual review, and not wearing people out with reviews of trivial changes.

2024-02-23 05:17 UTC, Nuru commented on CONTRIBUTING.md
> +The currently proposed labels are:
We have the `wip` and `do not merge` labels for PRs under active discussion and development. The `wip` (Work In Progress) label is for when the author does not consider the PR finalized, and has published it for comments and feedback on what is there but wants to add more before merging.

The `do not merge` label is for PRs in a state where releasing them would cause damage. It is along the lines of "changes requested", but can be used even when there are no proposed changes that would make the PR acceptable. 

I believe the standard label for preventing the "stale" label from being automatically applied is "frozen".

2024-02-23 05:19 UTC, Nuru commented on CONTRIBUTING.md
> +| ![`beginner`](https://img.shields.io/badge/beginner-388bfd)       | issues which should be a bit more involved than issues.                  |
As a side note: please add `?style=for-the-badge` to the end of shield image URLs, as in https://img.shields.io/badge/help_wanted-388bfd?style=for-the-badge

It is a new look we are adopting.

2024-02-23 05:22 UTC, Nuru commented on CONTRIBUTING.md
> +As a reference, the following is a mapping between labels and semver:
```suggestion
As a reference, the following is a mapping between labels and [semver](https://semver.org/):
```

2024-02-23 05:30 UTC, Nuru commented on CONTRIBUTING.md
> +make readme
We no longer use `make github/init`. 

```suggestion
make init
make readme
```

2024-02-23 05:58 UTC, Nuru requested changes
I made a bunch of comments. I will have more later, after I get some supporting documentation written or updated.

2024-02-23 05:58 UTC, Nuru commented on CONTRIBUTING.md
> +
There is also `go` test code using [terratest](https://github.com/gruntwork-io/terratest) under `test/src/` that may need to be updated, as the examples (always `examples/complete/`, usually other examples) are used for automated testing. 

Any changes to `versions.tf` in the module should also be made to `versions.tf` in `examples/complete/`

2024-02-23 05:58 UTC, Nuru commented on CONTRIBUTING.md
> +4. Configure the deprecated variable as a fallback of the replacement one, i.e. populate the value of the deprecated variable if the replacement variable is not supplied.
```suggestion
3. Add your replacement variable to `variables.tf`
4. Configure the deprecated variable as a fallback for the replacement one, i.e. use the value of the deprecated variable if it not the default value and the replacement variable is the default value. Otherwise, the replacement variable takes precedence.
```

2024-02-23 05:58 UTC, Nuru commented on CONTRIBUTING.md
> +To avoid errors like `The "count" value depends on resource attributes that cannot be determined until apply time, so Terraform cannot predict how many instances will be created. To work around this,
We run linters automatically now and they post comments on the PR if they find issues.

2024-02-23 05:58 UTC, Nuru commented on CONTRIBUTING.md
> +make docker/test
We do not expect you to run the tests locally. They are run against your PR by Cloud Posse automation via GitHub actions, and in some cases need additional credentials or infrastructure, which Cloud Posse supples. Also, we are not rigorous about ensuring that resources are deleted if the test crashes (rare, but not impossible), falling back on a nightly scheduled cleanup. We would not want you to be paying for abandoned resources if the test should crash. 

If you do want to run the tests locally anyway, you can:

```
cd test/src
make test
```

This requires that you have the applicable version of `go` installed.

As @hans-d mentioned, our current test tooling Docker images are only available for Intel, and the Makefile does not automatically pull cross-platform images. However, Apple can emulate Intel, so if you want to run the test inside a Docker container on an Apple CPU, all you have to do is manually pull the test image first:

```
docker pull --platform linux/amd64 cloudposse/test-harness:latest
```

2024-02-23 05:58 UTC, Nuru commented on CONTRIBUTING.md
> +To avoid errors like `The "count" value depends on resource attributes that cannot be determined until apply time, so Terraform cannot predict how many instances will be created. To work around this,
It looks like I'm going to have to write a document explaining maps vs lists as inputs. I hope to get you a better link than that wiki chapter on optional inputs, too.

2024-02-23 21:56 UTC, osterman commented on CONTRIBUTING.md
> +make docker/test
@Nuru I do not agree with this statement.

> We do not expect you to run the tests locally.

2024-02-24 15:20 UTC, hans-d commented on CONTRIBUTING.md
> +make docker/test
`--platform linux/amd64`  is something we can provide in the makefile (eg via env var). 
Now it needs to be done on a repo by repo base, but would rather have this a generic change.

2024-02-24 15:21 UTC, hans-d commented on CONTRIBUTING.md
> +make docker/test
> > We do not expect you to run the tests locally.
> It might have broke at some point, but it was always designed to run locally. When I was more active in development, used it all the time.

I prefer to be able to run all tests/checks/updates locally without having to rely on a pipeline, esp when someone needs to initiate that (as in these repos)

2024-02-24 23:45 UTC, joe-niland commented on CONTRIBUTING.md
> +To avoid errors like `The "count" value depends on resource attributes that cannot be determined until apply time, so Terraform cannot predict how many instances will be created. To work around this,
During development of a change I often run the tests locally. I've added a change to capture your tips @Nuru and also a warning about orphaned resources.

2024-02-24 23:49 UTC, joe-niland commented on CONTRIBUTING.md
> +The currently proposed labels are:
@Nuru I'm thinking this section should be removed for now until a final decision is made.

2024-02-24 23:54 UTC, joe-niland commented on CONTRIBUTING.md
> +1. `Patch`: A minor, backward compatible change. Increments patch version, e.g. 1.0.**1**
Thanks @Nuru
I have made some updates based on your comment, but you may want to add more in a future change.
Sometimes I find it difficult to determine the right label to use, so I think this section could benefit from some examples or at least better descriptions of each label.

2024-02-25 23:38 UTC, Nuru requested changes

2024-02-26 04:30 UTC, joe-niland commented on CONTRIBUTING.md
> +3. Add your replacement variable to `variables.tf`
I used VS Code to review the PR and this part seemed to have gotten mangled. Should be OK now.

2024-02-26 09:27 UTC, hans-d commented on CONTRIBUTING.md
> +make docker/test
Good to include that running this locally is more a strong suggestion vs mandatory - as it will improve the review cycle - and certainly helps with the more tricky changes

2024-02-26 11:01 UTC, joe-niland commented on CONTRIBUTING.md
> +make docker/test
Good point @hans-d - I've added a note about this

2024-02-26 20:59 UTC, merged